<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE student [
    <!ELEMENT student (firstName,lastName,studentId,subjectList?)>
    <!ELEMENT firstName (#PCDATA)>
    <!ELEMENT lastName (#PCDATA)>
    <!ELEMENT studentId (#PCDATA)>
    <!ELEMENT subjectList (subject+)>
    <!ELEMENT subject (subjectCode,creditPoints,mark,grade)>
    <!ELEMENT subjectCode (#PCDATA)>
    <!ELEMENT creditPoints (#PCDATA)>
    <!ELEMENT mark (#PCDATA)>
    <!ELEMENT grade (#PCDATA)>
]>

<student>
    <firstName>John</firstName>
    <lastName>Smith</lastName>
    <studentId>1231234</studentId>
    <subjectList>
        <subject>
            <subjectCode>MATH101</subjectCode>
            <creditPoints>4</creditPoints>
            <mark>85</mark>
            <grade>A</grade>
        </subject>

        <subject>
            <subjectCode>ECON111</subjectCode>
            <creditPoints>5</creditPoints>
            <mark>70</mark>
            <grade>B</grade>
        </subject>

        <subject>
            <subjectCode>CS100</subjectCode>
            <creditPoints>5</creditPoints>
            <mark>80</mark>
            <grade>A</grade>
        </subject>

        <subject>
            <subjectCode>LAW121</subjectCode>
            <creditPoints>6</creditPoints>
            <mark>75</mark>
            <grade>B</grade>
        </subject>
    </subjectList>
</student>